version: '3.8'

services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    networks:
      - laravel_net
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=adresse_ip_base_de_donnees
      - DB_PORT=3306
      - DB_DATABASE=nom_base
      - DB_USERNAME=utilisateur_base
      - DB_PASSWORD=mot_de_passe_base
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"  # Mappe le port 80 du conteneur au port 8080 du serveur
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
    networks:
      - laravel_net

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge