version: '3.8'

services:
  # Service Laravel
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage # Persistance des fichiers de stockage
    networks:
      - laravel_net
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=193.203.168.105
      - DB_PORT=3306
      - DB_DATABASE=u206274438_rpg_bdd
      - DB_USERNAME=u206274438_admin
      - DB_PASSWORD=pandoraEl8!bddcda
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      - redis

  # Service Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"  # Mappe le port 80 du conteneur au port 8080 de la machine
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Configuration personnalisée de Nginx
    depends_on:
      - laravel_app
    networks:
      - laravel_net

  # Service Redis
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
